### ISSUE TITLE
Add way to read sandbox files without parsing overhead

### ISSUE THREAD

**Issue by sadfun** [imachug/sunwalker-box#2]
For now, looks like that the only way to read files created inside sandbox is `cat` command. 

Sadly, it prints file as list of bytes, which is very inefficient: we should parse large JSON (due to printing bytes as integers, it can be larger then actual file **~4x times**!) and copy this heavy object firstly to stdout of `sunwalker-box`, then to memory of application which uses sunwalker-box.

It would be great to add something like a reverse bind to access sandbox files in zero-copy way.

**Comment by imachug** [comment]
Implemented in 6947f10
